name: FragmentsGem
version: '${project.version}'
main: br.com.fragmentsgem.FragmentsGem

commands:
  fragmentos:
    description: "Troque seus fragmentos por itens."
    permission: fragmentsgem.use
    permission-message: "&cVocê não tem permissão para usar este comando."
